import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import 'plyr/dist/plyr.css';
import { AuthProvider } from '@/hooks/useAuth';
import Footer from '@/components/Footer';
import Header from '@/components/Header';
import LiveStreamers from '@/components/LiveStreamers';
import { mockStreamers } from '@/data/mockData';
import { LayoutProvider } from '@/context/LayoutContext'

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} antialiased font-sans`}>
        <AuthProvider>
          <LayoutProvider>

            <Header />

            <LiveStreamers streamers={mockStreamers} />

            <div className="pl-0 md:pl-4 p-4 min-h-[calc(100vh-var(--navbar-height))] ml-[var(--sidebar-width-left)] mr-[var(--sidebar-width-right)] min-w-[calc(100vw-var(--sidebar-collapsed-width))] sm:min-w-auto transition-[padding,margin] duration-300 ease-in-out mt-[var(--navbar-height)] flex flex-col grow gap-6">
              <main className="grow space-y-6">
                {children}
              </main>
              <Footer />
            </div>

          </LayoutProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
