import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import 'plyr/dist/plyr.css';
import { AuthProvider } from '@/hooks/useAuth';
import Footer from '@/components/Footer';
import Header from '@/components/Header';
import LiveStreamers from '@/components/LiveStreamers';
import { mockStreamers } from '@/data/mockData';

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased font-sans`}>
        <AuthProvider>

            <Header />

            <div className="flex flex-col md:flex-row mt-20">
              <LiveStreamers streamers={mockStreamers} />

              <main className="md:basis-3/4 grow p-4 space-y-6 min-h-[calc(100vh-200px)]">

                {children}

              </main>

            </div>
            
          <Footer />
        </AuthProvider>
      </body>
    </html>
  );
}
