import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import 'plyr/dist/plyr.css';
import { AuthProvider } from '@/hooks/useAuth';
import Footer from '@/components/Footer';
import Header from '@/components/Header';
import LiveStreamers from '@/components/LiveStreamers';
import { mockStreamers } from '@/data/mockData';
import { LayoutProvider } from '@/context/LayoutContext'

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} antialiased font-sans`}>
        <AuthProvider>
          <LayoutProvider>

            <Header />

            <LiveStreamers streamers={mockStreamers} />

            <main className="pl-0 md:pl-4 p-4 space-y-6 min-h-screen ml-[var(--sidebar-width-left)] mr-[var(--sidebar-width-right)] min-w-[calc(100vw-var(--sidebar-collapsed-width))] sm:min-w-fit transition-[padding,margin] duration-300 ease-in-out mt-[var(--navbar-height)]">
              {children}
            </main>

            <Footer />
          </LayoutProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
